### ISSUE TITLE
Example has memory leak issue

### ISSUE THREAD

**Issue by tony-tang** [asaia/StarlingPunk#1]
Hi, there is a memory leak issue in your example. Please look up the patch.

---

diff --git a/src/com/saia/starlingPunkExample/worlds/PlayWorld.as b/src/com/saia/starlingPunkExample/worlds/PlayWorld.as
index 6727dd9..dfc2cc0 100644
--- a/src/com/saia/starlingPunkExample/worlds/PlayWorld.as
+++ b/src/com/saia/starlingPunkExample/worlds/PlayWorld.as
@@ -7,9 +7,11 @@
    import com.saia.starlingPunkExample.controller.ScoreController;
    import com.saia.starlingPunkExample.entities.AlienEntity;
    import com.saia.starlingPunkExample.entities.PlayerEntity;
-   
  import flash.display.BitmapData;
  import flash.events.TimerEvent;
  import flash.utils.Timer;
-   
  import starling.display.Image;
  import starling.textures.Texture;

@@ -21,6 +23,7 @@
    {
        private var _enemySpawnTimer:Number;
        private var _player:PlayerEntity;
- ```
    private var timer:Timer;
  public function PlayWorld() 
  {
  }
  ```
  
  @@ -35,7 +38,7 @@
          createBgFill();
  
  ```
      _enemySpawnTimer = 500;
  ```
-           var timer:Timer = new Timer(_enemySpawnTimer);
-           timer = new Timer(_enemySpawnTimer);
          timer.addEventListener(TimerEvent.TIMER, onEnemySpawnTimer);
          timer.start();

@@ -57,6 +60,9 @@
        override public function end():void 
        {
            super.end();
-           timer.removeEventListener(TimerEvent.TIMER, onEnemySpawnTimer);
-           timer.stop();
-           timer = null;
          removeAll();
      }

**Comment by asaia** [comment]
Yeah I made the example game really quickly just to get people started with the framework... good find just pushed the fix
