### ISSUE TITLE
tmx extension

### ISSUE THREAD

**Issue by freddymx** [asaia/StarlingPunk#3]
Have you seen this extension http://flashpunk.net/forums/index.php?topic=2654.0 ? Is it possible in starling-punk?

**Comment by Kamek** [comment]
That would be awesome, there's also [this one](http://wiki.starling-framework.org/extensions/tmx_loader) as well.

**Comment by asaia** [comment]
It's pretty incredible that there's so many high quality cheap/free tile editors out there. The only problem is I won't be able to make an extension for all of them myself. StalingPunks Tilemap and Grid classes make building your own pretty easy though... it's just a matter of parsing the xml files each particular tile editor spits out.

it would look something like this:

var tilemap:SPTilemap = new SPTilemap(SP.width, SP.height, 32, 32);
tilemap.loadFromString(levelDataBitString);

//handles the collision detection of the tiles
var grid:SPGrid = new SPGrid(SP.width, SP.height, 32, 32);
grid.loadFromString(levelDataBitString);
this.mask = grid;

My hope is that the community will start creating their own extensions for StarlingPunk... Pierre Chamberlain is already making some great progress on a PyxelEdit extension:
http://pierrechamberlain.ca/blog/2012/08/preview-pyxeledit-tilemaps-implemented-starlingpunk/

**Comment by smithmj5** [comment]
I'm currently working on an extension for StarlingPunk to use Tiled maps, since that's my editor of choice.  Will share once done!  And yeah, it actually looks pretty straightforward to implement.  Thanks for a great engine asaia!
