### ISSUE TITLE
Multiple ShakeEffects can cause the world.x and y to end at a wrong point

### ISSUE THREAD

**Issue by dedsmed** [asaia/StarlingPunk#6]
I found that if 2 or more shakeeffects are created with overlapping durations(one is 1 second, and another is started halfway through it that is also 1 second), then after the last one finishes the World.x and World.y won't always be correct.

The reason why -

In ShakeEffect constructor SP.world.x, and SP.world.y are set as _startPos

IF a shake is currently in effect, then the SP.world.x, and y are currently being randomized, so when the second one goes to grab the x,y coordinates it's grabbing ones that are already offset; therefore the "startpoint" isn't techincally the correct startpoint.

**Comment by asaia** [comment]
Thanks dedsmed I'm planning another commit really soon and I'll fix this when I push the rest

**Comment by dedsmed** [comment]
No problem.  Keep up the good work, I'm really enjoying StarlingPunk - it's been a fairly easy transition from flixel.
