### ISSUE TITLE
SPGrid collision mask

### ISSUE THREAD

**Issue by Drabuna** [asaia/StarlingPunk#8]
When using large SPTilemap and SPGrid to handle collisions, there is a bug, when entity moves out of game rectangle, and collision detection no longer occurs.

My fix was - SpriteCanvas.as, function checkSpriteVisibilites, replace:

_spriteRect.x = x \* SP.width;
_spriteRect.y = y \* SP.height;

with:

_spriteRect.x = _rect.x;
_spriteRect.y = _rect.y;

Don't know how optimal this is, but it seems to fix the issue.

UPD: no, on even bigger maps issue still exists.
UPD2: oh, setHitWidht, setHitHeight fixes the issue, sry.

**Comment by asaia** [comment]
Whoa that is a big bug..... good find I'll push a patch through as soon as I can.
